### PR TITLE
small modules bugs

### PR DESCRIPTION
**Pull request by Henry-E**
A couple of small bugs that happen when running `interact`. They're just missing the module calls.

### CODE REVIEW

**Comment by vansky** [comment]
Thanks for catching those. I made a few changes to your PR, but I wasn't able to merge them into it. There are instructions for how to allow a merge [here](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/). Alternatively, you can make the changes on your end.

I think the test_evaluate change could be better modeled by having `interact` force `args.single = True` around line 123 since interactivity will preclude processing multiple sentences in parallel. In fact, I may actually want to make `words` force `single` as well, but I'll need to think about whether there is any reason not to.

The `flatten_parameters` issue needs to be fixed for non-interactive settings, though. In order to still work for people using `single`, it needs a check and a non-module case.

**Comment by Henry-E** [comment]
Weird, it has "allow edits from maintainers" checked.

Anyway, feel free to make the changes yourself and I'll close the pull request. There was another missing one from `generation.py` https://github.com/vansky/neural-complexity/blob/master/generate.py#L64

**Comment by vansky** [comment]
Looks like I just messed up the merge. Go ahead and make your changes in `generation.py`, and once I get a chance to test these changes, I'll merge the PR.

**Comment by Henry-E** [comment]
Ok the additional module call required for generate is added

**Pull request merged**
